# Generated by Django 5.2 on 2025-05-11 20:32

from django.db import migrations, models

def generate_unique_codes(apps, schema_editor):
    Course = apps.get_model('administration', 'Course')
    for course in Course.objects.all():
        course.code = f"COURSE{course.pk}"
        course.save(update_fields=['code'])

class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=20, default='', blank=True),
        ),
        migrations.RunPython(generate_unique_codes, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=20, unique=True, default=''),
        ),
    ]
