# Generated by Django 5.2 on 2025-05-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='UNKN101', max_length=20, unique=True),
        ),
    ]
