# Generated by Django 5.2 on 2025-05-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(default='UNKN101', max_length=20),
        ),
    ]
