# Generated by Django 5.2.1 on 2025-05-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_overriderequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='UNKN101', max_length=20, unique=True),
        ),
    ]
